package Com.Artek;
// Generated 8 Jul, 2017 1:33:49 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Manager generated by hbm2java
 */
@Entity
@Table(name = "manager", catalog = "Event_mgmt_anot")
public class Manager implements java.io.Serializable {

	private Integer managerid;
	private String managerName;
	private Set<Event> events = new HashSet<Event>(0);

	public Manager() {
	}

	public Manager(String managerName, Set<Event> events) {
		this.managerName = managerName;
		this.events = events;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "managerid", unique = true, nullable = false)
	public Integer getManagerid() {
		return this.managerid;
	}

	public void setManagerid(Integer managerid) {
		this.managerid = managerid;
	}

	@Column(name = "managerName")
	public String getManagerName() {
		return this.managerName;
	}

	public void setManagerName(String managerName) {
		this.managerName = managerName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "manager")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

}
