package Com.Artek;
// Generated 8 Jul, 2017 12:00:04 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "event", catalog = "Event_mgmt")
public class Event implements java.io.Serializable {

	private int eventid;
	private Company company;
	private String eventName;
	private Set<Audiance> audiances = new HashSet<Audiance>(0);
	private Set<Location> locations = new HashSet<Location>(0);

	public Event() {
	}

	public Event(int eventid) {
		this.eventid = eventid;
	}

	public Event(int eventid, Company company, String eventName, Set<Audiance> audiances, Set<Location> locations) {
		this.eventid = eventid;
		this.company = company;
		this.eventName = eventName;
		this.audiances = audiances;
		this.locations = locations;
	}

	@Id

	@Column(name = "Eventid", unique = true, nullable = false)
	public int getEventid() {
		return this.eventid;
	}

	public void setEventid(int eventid) {
		this.eventid = eventid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "foreventid")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "EventName")
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
	public Set<Audiance> getAudiances() {
		return this.audiances;
	}

	public void setAudiances(Set<Audiance> audiances) {
		this.audiances = audiances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
	public Set<Location> getLocations() {
		return this.locations;
	}

	public void setLocations(Set<Location> locations) {
		this.locations = locations;
	}

}
