package Com.Artek;
// Generated 8 Jul, 2017 12:00:04 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", catalog = "Event_mgmt")
public class Location implements java.io.Serializable {

	private int locationid;
	private Event event;
	private String locationName;

	public Location() {
	}

	public Location(int locationid) {
		this.locationid = locationid;
	}

	public Location(int locationid, Event event, String locationName) {
		this.locationid = locationid;
		this.event = event;
		this.locationName = locationName;
	}

	@Id

	@Column(name = "locationid", unique = true, nullable = false)
	public int getLocationid() {
		return this.locationid;
	}

	public void setLocationid(int locationid) {
		this.locationid = locationid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "event")
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@Column(name = "locationName")
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

}
