package Com.Artek;
// Generated 8 Jul, 2017 12:00:04 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Manager generated by hbm2java
 */
@Entity
@Table(name = "manager", catalog = "Event_mgmt")
public class Manager implements java.io.Serializable {

	private int managerid;
	private String managerName;

	public Manager() {
	}

	public Manager(int managerid) {
		this.managerid = managerid;
	}

	public Manager(int managerid, String managerName) {
		this.managerid = managerid;
		this.managerName = managerName;
	}

	@Id

	@Column(name = "Managerid", unique = true, nullable = false)
	public int getManagerid() {
		return this.managerid;
	}

	public void setManagerid(int managerid) {
		this.managerid = managerid;
	}

	@Column(name = "ManagerName")
	public String getManagerName() {
		return this.managerName;
	}

	public void setManagerName(String managerName) {
		this.managerName = managerName;
	}

}
